In [17]:
from numpy import *

b = array(
    [
        [16],
        [8],
        [-8],
        [-32]
    ]
)

V = array(
    [
        [1, 0],
        [0, 1]
    ]
)

U = array(
    [
        [0.5, 0.5, 0.5, 0],
        [-0.5, 0.5, 0, 0.5],
        [-0.5, 0.5, 0, -0.5],
        [0.5, 0.5, -0.5, 0]
    ]
)

S = array(
    [
        [2, 0],
        [0, 2],
        [0, 0],
        [0, 0]
    ]
)

S_D = array(
    [
        [0.5, 0, 0, 0],
        [0, 0.5, 0, 0]
    ]
)

A_D = V @ S_D @ U.T
x = A_D @ b
x

array([[-4.],
       [-4.]])

In [21]:
from numpy import *

def heunn(x0, f, t0, tf, n):
    """ Calcula la evolución del sistema o ecuación diferencial empleando como método de aproximación
        el método de Heunn, un método Runge Kutta de segundo orden que emplea aproximación por el área del trapecio.
        :parametro x0: Estado inicial, condiciones iniciales
        :parametro f: Función de carga f(t,x)
        :parametro t0: Tiempo inicial
        :parametro tf: Tiempo final
        :parametro n: Cantidad de puntos
    """
    h = (tf - t0) / n
    t = [t0]
    x = [x0]
    for i in range(1, n+1):
        t.append(t[i - 1] + h)
        k1 = f(t[i-1], x[i-1])
        k2 = f(t[i-1] + h, x[i - 1] + h * k1)
        x.append(x[i - 1] + 0.5 * h * (k1 + k2))
    return array(t), array(x)

print("Ejercicio 4.a")
f = lambda t, y: cos(y + t)
t0 = 0
tf = 0.2
n = 2
x0 = 0
print(heunn(x0, f, t0, tf, n))

print("Ejercicio 4.b")
n = 4
x0 = 0
print(heunn(x0, f, t0, tf, n))

print("Ejercicio 4.d")
n = 52
x0 = 0
print(heunn(x0, f, t0, tf, n))

Ejercicio 4.a
(array([0. , 0.1, 0.2]), array([0.        , 0.09900333, 0.19412721]))
Ejercicio 4.b
(array([0.  , 0.05, 0.1 , 0.15, 0.2 ]), array([0.        , 0.0498751 , 0.09925404, 0.1476556 , 0.19462678]))
Ejercicio 4.d
(array([0.        , 0.00384615, 0.00769231, 0.01153846, 0.01538462,
       0.01923077, 0.02307692, 0.02692308, 0.03076923, 0.03461538,
       0.03846154, 0.04230769, 0.04615385, 0.05      , 0.05384615,
       0.05769231, 0.06153846, 0.06538462, 0.06923077, 0.07307692,
       0.07692308, 0.08076923, 0.08461538, 0.08846154, 0.09230769,
       0.09615385, 0.1       , 0.10384615, 0.10769231, 0.11153846,
       0.11538462, 0.11923077, 0.12307692, 0.12692308, 0.13076923,
       0.13461538, 0.13846154, 0.14230769, 0.14615385, 0.15      ,
       0.15384615, 0.15769231, 0.16153846, 0.16538462, 0.16923077,
       0.17307692, 0.17692308, 0.18076923, 0.18461538, 0.18846154,
       0.19230769, 0.19615385, 0.2       ]), array([0.        , 0.0038461 , 0.00769197, 0.01153738, 0.015382